# Name of the GitHub Actions workflow
name: Run Python Script and Push Changes

# Define the events that trigger this workflow
on:
  # Run automatically on a schedule (daily at midnight UTC)
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00 UTC
  # Allow the workflow to be manually triggered from the GitHub UI
  workflow_dispatch:

# Define the set of jobs to run
jobs:
  # Name of the job
  build:
    name: Execute Python Script and Push Changes
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code onto the runner
      - name: Check out code
        uses: actions/checkout@v4

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run the Python script
      - name: Run Python script
        run: python main.py

      # Commit and push any file changes made by the script
      - name: Push updated files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto update: $(date)"
            git push
          else
            echo "No changes to commit."
